name: Draw Keymap

on:
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string
      destination:
        required: false
        type: string
        default: "commit"
      fail_on_error:
        required: false
        type: boolean
        default: true

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - name: Call keymap-drawer reusable workflow
        uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
        with:
          commit_message: ${{ inputs.commit_message }}
          destination: ${{ inputs.destination }}
          fail_on_error: ${{ inputs.fail_on_error }}
        