name: Draw Keymap
on:
  workflow_run:
    workflows: ["Build ZMK firmware"]
    types:
      - completed

jobs:
  draw:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.workflow_run.head_commit.message }}"
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
